// ─── FORM16 TRANSLATIONS ─────────────────────────────────────────────────────
// Supported languages: en (English), ru (Russian)
// Usage: t("key") returns string in current language
// Usage: t("key", { name: "Alex" }) for interpolation → replaces {name}

export const LANGUAGES = [
  { code: "en", label: "English", flag: "🇬🇧" },
  { code: "ru", label: "Русский", flag: "🇷🇺" },
];

export const TRANSLATIONS = {

  // ─── SPLASH ───────────────────────────────────────────────────────────────
  "splash.tagline1":        { en: "16 weeks.", ru: "16 недель." },
  "splash.tagline2":        { en: "Transform", ru: "Трансформация" },
  "splash.tagline3":        { en: "for good.", ru: "навсегда." },
  "splash.subtitle":        { en: "Science-backed program with daily habits, nutrition tracking, and real results.", ru: "Научно обоснованная программа с ежедневными привычками, отслеживанием питания и реальными результатами." },
  "splash.feature1":        { en: "Real daily tasks from a 16-week program", ru: "Реальные ежедневные задания из 16-недельной программы" },
  "splash.feature2":        { en: "FatSecret food diary sync", ru: "Синхронизация дневника питания FatSecret" },
  "splash.feature3":        { en: "Training, nutrition & mindset per week", ru: "Тренировки, питание и психология каждую неделю" },
  "splash.feature4":        { en: "Duolingo-style streaks & XP", ru: "Серии и XP в стиле Duolingo" },
  "splash.feature5":        { en: "Coach dashboard for trainers", ru: "Панель тренера" },
  "splash.start":           { en: "Start my transformation →", ru: "Начать трансформацию →" },
  "splash.coach":           { en: "Coach / Trainer login", ru: "Вход для тренера" },
  "splash.signin":          { en: "I already have an account", ru: "У меня уже есть аккаунт" },

  // ─── LANGUAGE PICKER ──────────────────────────────────────────────────────
  "lang.choose":            { en: "Choose your language", ru: "Выберите язык" },
  "lang.subtitle":          { en: "You can change this later in your profile", ru: "Вы можете изменить это в профиле" },
  "lang.continue":          { en: "Continue", ru: "Продолжить" },

  // ─── AUTH ─────────────────────────────────────────────────────────────────
  "auth.welcome_back":      { en: "Welcome back", ru: "С возвращением" },
  "auth.create_account":    { en: "Create account", ru: "Создать аккаунт" },
  "auth.signin_subtitle":   { en: "Sign in to continue your journey", ru: "Войдите, чтобы продолжить" },
  "auth.signup_subtitle":   { en: "Start your 16-week transformation", ru: "Начните 16-недельную трансформацию" },
  "auth.google":            { en: "Continue with Google", ru: "Войти через Google" },
  "auth.or":                { en: "or", ru: "или" },
  "auth.email":             { en: "Email address", ru: "Электронная почта" },
  "auth.password":          { en: "Password", ru: "Пароль" },
  "auth.signin_btn":        { en: "Sign In", ru: "Войти" },
  "auth.signup_btn":        { en: "Create Account", ru: "Создать аккаунт" },
  "auth.loading":           { en: "Loading…", ru: "Загрузка…" },
  "auth.no_account":        { en: "Don't have an account? ", ru: "Нет аккаунта? " },
  "auth.has_account":       { en: "Already have an account? ", ru: "Уже есть аккаунт? " },
  "auth.signup_link":       { en: "Sign up", ru: "Зарегистрироваться" },
  "auth.signin_link":       { en: "Sign in", ru: "Войти" },
  "auth.fill_fields":       { en: "Please fill in both fields.", ru: "Пожалуйста, заполните оба поля." },
  "auth.check_email":       { en: "Check your email for a confirmation link.", ru: "Проверьте почту — мы отправили ссылку для подтверждения." },

  // ─── ONBOARDING STEPS ─────────────────────────────────────────────────────
  "step.1.title":           { en: "Create your account", ru: "Создайте аккаунт" },
  "step.1.sub":             { en: "Step 1 of 6", ru: "Шаг 1 из 6" },
  "step.2.title":           { en: "Your body stats", ru: "Параметры тела" },
  "step.2.sub":             { en: "Step 2 of 6", ru: "Шаг 2 из 6" },
  "step.3.title":           { en: "Body measurements", ru: "Обмеры тела" },
  "step.3.sub":             { en: "Step 3 of 6", ru: "Шаг 3 из 6" },
  "step.4.title":           { en: "Your goal", ru: "Ваша цель" },
  "step.4.sub":             { en: "Step 4 of 6", ru: "Шаг 4 из 6" },
  "step.5.title":           { en: "Your lifestyle", ru: "Ваш образ жизни" },
  "step.5.sub":             { en: "Step 5 of 6", ru: "Шаг 5 из 6" },
  "step.6.title":           { en: "Activity level", ru: "Уровень активности" },
  "step.6.sub":             { en: "Step 6 of 6", ru: "Шаг 6 из 6" },
  "onboarding.continue":    { en: "Continue →", ru: "Продолжить →" },
  "onboarding.finish":      { en: "Start my 16-week journey 🚀", ru: "Начать 16-недельный путь 🚀" },

  // ─── STEP 1: Account ──────────────────────────────────────────────────────
  "field.name":             { en: "Full Name", ru: "Полное имя" },
  "field.name.ph":          { en: "e.g. Alex Johnson", ru: "напр. Иван Петров" },
  "field.email":            { en: "Email", ru: "Электронная почта" },
  "field.email.ph":         { en: "you@example.com", ru: "вы@example.com" },
  "field.password":         { en: "Password", ru: "Пароль" },
  "field.password.ph":      { en: "At least 6 characters", ru: "Минимум 6 символов" },

  // ─── STEP 2: Body stats ───────────────────────────────────────────────────
  "field.gender":           { en: "Gender", ru: "Пол" },
  "field.gender.male":      { en: "Male", ru: "Мужской" },
  "field.gender.female":    { en: "Female", ru: "Женский" },
  "field.age":              { en: "Age", ru: "Возраст" },
  "field.age.ph":           { en: "e.g. 28", ru: "напр. 28" },
  "field.age.unit":         { en: "years", ru: "лет" },
  "field.height":           { en: "Height", ru: "Рост" },
  "field.height.ph":        { en: "e.g. 178", ru: "напр. 178" },
  "field.weight":           { en: "Current Weight", ru: "Текущий вес" },
  "field.weight.ph":        { en: "e.g. 84.5", ru: "напр. 84.5" },
  "bmi.underweight":        { en: "Underweight", ru: "Недостаточный вес" },
  "bmi.normal":             { en: "Normal", ru: "Норма" },
  "bmi.overweight":         { en: "Overweight", ru: "Избыточный вес" },
  "bmi.obese":              { en: "Obese", ru: "Ожирение" },
  "stats.tdee":             { en: "kcal / day", ru: "ккал / день" },

  // ─── STEP 3: Measurements ─────────────────────────────────────────────────
  "measure.intro":          { en: "Stand relaxed. Measure at the end of a normal exhale. Don't suck in.", ru: "Встаньте расслабленно. Измеряйте после обычного выдоха. Не втягивайте живот." },
  "measure.howto":          { en: "How to measure correctly:", ru: "Как правильно измерять:" },
  "measure.waist":          { en: "Waist", ru: "Талия" },
  "measure.waist.desc":     { en: "Measure around your navel. Snug but not compressing skin.", ru: "Измеряйте на уровне пупка. Лента должна прилегать, но не давить." },
  "measure.waist.ph":       { en: "e.g. 88", ru: "напр. 88" },
  "measure.neck":           { en: "Neck", ru: "Шея" },
  "measure.neck.desc":      { en: "Just below the larynx, sloping slightly downward toward the front.", ru: "Чуть ниже гортани (кадыка), слегка наклоняясь вниз к передней части." },
  "measure.neck.ph":        { en: "e.g. 38", ru: "напр. 38" },
  "measure.thigh":          { en: "Thigh", ru: "Бедро" },
  "measure.thigh.desc":     { en: "Upper thigh at widest point, weight evenly distributed.", ru: "Верхняя часть бедра в самом широком месте, вес распределён равномерно." },
  "measure.thigh.ph":       { en: "e.g. 56", ru: "напр. 56" },
  "measure.bfp":            { en: "Estimated Body Fat % (US Navy)", ru: "Процент жира (формула ВМС США)" },
  "measure.bfp.updates":    { en: "Updates as you log new measurements", ru: "Обновляется при добавлении новых замеров" },

  // ─── STEP 4: Goal ─────────────────────────────────────────────────────────
  "goal.label":             { en: "Primary Goal", ru: "Основная цель" },
  "goal.fat_loss":          { en: "Fat Loss", ru: "Снижение жира" },
  "goal.fat_loss.desc":     { en: "Lose body fat while preserving muscle. Calorie deficit with high protein.", ru: "Снизить жир, сохранив мышцы. Дефицит калорий с высоким содержанием белка." },
  "goal.recomp":            { en: "Body Recomposition", ru: "Рекомпозиция тела" },
  "goal.recomp.desc":       { en: "Lose fat and gain muscle simultaneously. Slower but sustainable.", ru: "Одновременно снижать жир и набирать мышцы. Медленнее, но устойчиво." },
  "goal.health":            { en: "General Health", ru: "Общее здоровье" },
  "goal.health.desc":       { en: "Build consistent habits around movement, sleep, nutrition, and stress.", ru: "Формировать устойчивые привычки: движение, сон, питание, управление стрессом." },

  // ─── STEP 5: Lifestyle ────────────────────────────────────────────────────
  "lifestyle.stress":       { en: "Stress level in daily life", ru: "Уровень стресса в повседневной жизни" },
  "lifestyle.stress.low":   { en: "Very calm", ru: "Очень спокойно" },
  "lifestyle.stress.high":  { en: "Very stressed", ru: "Очень стрессово" },
  "lifestyle.sleep":        { en: "Sleep quality", ru: "Качество сна" },
  "lifestyle.sleep.low":    { en: "Deep & restful", ru: "Глубокий и спокойный" },
  "lifestyle.sleep.high":   { en: "Broken / poor", ru: "Прерывистый / плохой" },
  "lifestyle.diet":         { en: "Current diet quality", ru: "Качество питания сейчас" },
  "lifestyle.diet.low":     { en: "Very clean", ru: "Очень чистое" },
  "lifestyle.diet.high":    { en: "Very processed", ru: "Очень переработанное" },
  "lifestyle.training":     { en: "How often do you train?", ru: "Как часто вы тренируетесь?" },
  "training.none":          { en: "No training / spontaneous", ru: "Без тренировок / спонтанно" },
  "training.none.desc":     { en: "No structured workouts. Maybe occasional walks, nothing planned.", ru: "Без структурированных тренировок. Возможно, редкие прогулки, ничего запланированного." },
  "training.1_2x":          { en: "1–2 times per week", ru: "1–2 раза в неделю" },
  "training.1_2x.desc":     { en: "Occasional training. A session here and there, not yet a fixed routine.", ru: "Периодические тренировки. Сессия то там, то тут — без фиксированного расписания." },
  "training.3plus":         { en: "3 or more times per week", ru: "3 и более раз в неделю" },
  "training.3plus.desc":    { en: "Regular training with a clear structure and consistent schedule.", ru: "Регулярные тренировки с чёткой структурой и постоянным расписанием." },
  "experience.label":       { en: "Training experience", ru: "Опыт тренировок" },
  "experience.beginner":    { en: "Beginner", ru: "Начинающий" },
  "experience.beginner.desc": { en: "Just starting out — up to 6 months of consistent training.", ru: "Только начинаете — до 6 месяцев регулярных тренировок." },
  "experience.intermediate": { en: "Intermediate", ru: "Средний уровень" },
  "experience.intermediate.desc": { en: "6–12 months. You know the basics and follow a programme.", ru: "6–12 месяцев. Знаете основы и следуете программе." },
  "experience.advanced":    { en: "Advanced", ru: "Продвинутый" },
  "experience.advanced.desc": { en: "More than 1 year. Strong technique, progressive overload, clear goals.", ru: "Более 1 года. Хорошая техника, прогрессивная нагрузка, чёткие цели." },

  // ─── STEP 6: Activity ─────────────────────────────────────────────────────
  "activity.note":          { en: "Daily life activity — not counting your workouts. How much do you move outside the gym?", ru: "Активность в повседневной жизни — без учёта тренировок. Насколько вы двигаетесь вне зала?" },
  "activity.sedentary":     { en: "Sedentary", ru: "Сидячий образ жизни" },
  "activity.sedentary.desc": { en: "Desk job, little walking. Mostly sitting. Under 4,000 steps typically.", ru: "Офисная работа, мало ходьбы. В основном сижу. Обычно менее 4 000 шагов." },
  "activity.light":         { en: "Lightly Active", ru: "Слабо активный" },
  "activity.light.desc":    { en: "Some walking or light movement. Office worker who walks at lunch.", ru: "Немного ходьбы или лёгких движений. Офисный работник, выходящий на прогулку в обед." },
  "activity.moderate":      { en: "Moderately Active", ru: "Умеренно активный" },
  "activity.moderate.desc": { en: "On your feet a good portion of the day. ~7,000–10,000 steps.", ru: "Большую часть дня на ногах. ~7 000–10 000 шагов." },
  "activity.active":        { en: "Active", ru: "Активный" },
  "activity.active.desc":   { en: "Physical job. Construction, nursing, lots of walking and manual tasks.", ru: "Физическая работа. Строительство, медицина, много ходьбы и ручного труда." },
  "activity.veryActive":    { en: "Very Active", ru: "Очень активный" },
  "activity.veryActive.desc": { en: "Extremely physical lifestyle. Manual labour all day long.", ru: "Крайне физический образ жизни. Ручной труд весь день." },
  "fatsecret.toggle":       { en: "FatSecret", ru: "FatSecret" },
  "fatsecret.toggle.sub":   { en: "Auto-sync food diary", ru: "Автосинхронизация дневника питания" },
  "fatsecret.toggle.note":  { en: "You'll connect after account creation", ru: "Подключите после создания аккаунта" },
  "summary.title":          { en: "Profile Summary", ru: "Сводка профиля" },
  "summary.name":           { en: "Name", ru: "Имя" },
  "summary.goal":           { en: "Goal", ru: "Цель" },
  "summary.weight":         { en: "Weight", ru: "Вес" },
  "summary.trains":         { en: "Trains", ru: "Тренировки" },
  "summary.experience":     { en: "Experience", ru: "Опыт" },

  // ─── DASHBOARD HEADER ─────────────────────────────────────────────────────
  "header.welcome":         { en: "Welcome back", ru: "С возвращением" },
  "header.streak":          { en: "streak", ru: "серия" },
  "header.signout":         { en: "Sign out", ru: "Выйти" },

  // ─── TABS ─────────────────────────────────────────────────────────────────
  "tab.today":              { en: "Today", ru: "Сегодня" },
  "tab.program":            { en: "Program", ru: "Программа" },
  "tab.progress":           { en: "Progress", ru: "Прогресс" },
  "tab.profile":            { en: "Profile", ru: "Профиль" },

  // ─── TODAY TAB ────────────────────────────────────────────────────────────
  "today.task":             { en: "Today's Task", ru: "Задание дня" },
  "today.log":              { en: "+ Log Day", ru: "+ Записать день" },
  "today.logged":           { en: "✓ Logged", ru: "✓ Записано" },
  "today.nutrition":        { en: "This week's nutrition focus", ru: "Фокус питания этой недели" },
  "today.weight":           { en: "Weight", ru: "Вес" },
  "today.bodyfat":          { en: "Body Fat", ru: "Жир в теле" },
  "today.trend":            { en: "Weight trend", ru: "Динамика веса" },
  "today.metrics":          { en: "Today's Metrics", ru: "Показатели дня" },
  "today.no_log":           { en: "Tap + Log Day to record today's metrics", ru: "Нажмите + Записать день, чтобы внести показатели" },
  "today.navy":             { en: "US Navy estimate", ru: "Оценка по методу ВМС США" },
  "today.since_start":      { en: "since start", ru: "с начала" },
  "today.week_details":     { en: "Week {w} details →", ru: "Детали недели {w} →" },

  // ─── LOG MODAL ────────────────────────────────────────────────────────────
  "log.title":              { en: "Log Today", ru: "Записать сегодня" },
  "log.sync":               { en: "⚡ Sync FatSecret", ru: "⚡ Синхр. FatSecret" },
  "log.syncing":            { en: "Syncing…", ru: "Синхронизация…" },
  "log.synced":             { en: "✓ Synced", ru: "✓ Синхронизировано" },
  "log.synced.note":        { en: "✓ Calories and protein filled from your FatSecret diary", ru: "✓ Калории и белок заполнены из дневника FatSecret" },
  "log.weight":             { en: "Weight", ru: "Вес" },
  "log.calories":           { en: "Calories", ru: "Калории" },
  "log.protein":            { en: "Protein", ru: "Белок" },
  "log.steps":              { en: "Steps", ru: "Шаги" },
  "log.save":               { en: "Save Today's Log ✓", ru: "Сохранить запись дня ✓" },
  "log.weight.ph":          { en: "e.g. 83.8", ru: "напр. 83.8" },
  "log.calories.ph":        { en: "e.g. 2050", ru: "напр. 2050" },
  "log.protein.ph":         { en: "e.g. 155", ru: "напр. 155" },
  "log.steps.ph":           { en: "e.g. 9400", ru: "напр. 9400" },

  // ─── METRICS ──────────────────────────────────────────────────────────────
  "metric.calories":        { en: "Calories", ru: "Калории" },
  "metric.protein":         { en: "Protein", ru: "Белок" },
  "metric.steps":           { en: "Steps", ru: "Шаги" },

  // ─── PROGRAM TAB ──────────────────────────────────────────────────────────
  "program.title":          { en: "16-Week Journey", ru: "16-недельный путь" },
  "program.tap":            { en: "Tap any week to see training, nutrition & mindset details", ru: "Нажмите на неделю, чтобы увидеть тренировки, питание и психологию" },
  "program.active":         { en: "ACTIVE", ru: "АКТИВНА" },
  "week.detail.days":       { en: "📅 Days", ru: "📅 Дни" },
  "week.detail.training":   { en: "🏋️ Training", ru: "🏋️ Тренировка" },
  "week.detail.nutrition":  { en: "🥗 Nutrition", ru: "🥗 Питание" },
  "week.detail.mindset":    { en: "🧠 Mindset", ru: "🧠 Психология" },
  "week.overview":          { en: "Week Overview", ru: "Обзор недели" },
  "week.focus":             { en: "Weekly Focus", ru: "Фокус недели" },
  "week.practice":          { en: "🧘 Daily Practice", ru: "🧘 Ежедневная практика" },
  "week.meal":              { en: "Meal Idea", ru: "Идея блюда" },
  "week.theme":             { en: "This Week's Theme", ru: "Тема недели" },
  "training.sets":          { en: "sets", ru: "подходы" },
  "training.intensity":     { en: "Intensity", ru: "Интенсивность" },
  "training.duration":      { en: "min", ru: "мин" },
  "protein.per.kg":         { en: "g protein/kg", ru: "г белка/кг" },
  "day.label":              { en: "Day", ru: "День" },
  "xp.label":               { en: "XP on completion", ru: "XP за выполнение" },

  // ─── PROGRESS TAB ─────────────────────────────────────────────────────────
  "progress.title":         { en: "Progress Reports", ru: "Отчёты о прогрессе" },
  "progress.start":         { en: "Start", ru: "Начало" },
  "progress.current":       { en: "Current", ru: "Сейчас" },
  "progress.lost":          { en: "Lost", ru: "Потеряно" },
  "progress.gained":        { en: "Gained", ru: "Набрано" },
  "progress.bodyfat":       { en: "Body Fat", ru: "Жир в теле" },
  "progress.bmi":           { en: "BMI", ru: "ИМТ" },
  "progress.trend":         { en: "Weight Trend", ru: "Динамика веса" },
  "progress.tracked":       { en: "{n} days tracked", ru: "Отслежено дней: {n}" },
  "progress.averages":      { en: "7-Day Averages", ru: "Средние за 7 дней" },
  "progress.log":           { en: "Daily Log", ru: "Ежедневный журнал" },
  "progress.no_trend":      { en: "Log more days to see your trend", ru: "Записывайте больше дней, чтобы увидеть динамику" },

  // ─── PROFILE TAB ──────────────────────────────────────────────────────────
  "profile.body_stats":     { en: "Body Stats", ru: "Параметры тела" },
  "profile.age":            { en: "Age", ru: "Возраст" },
  "profile.height":         { en: "Height", ru: "Рост" },
  "profile.weight":         { en: "Weight", ru: "Вес" },
  "profile.bmi":            { en: "BMI", ru: "ИМТ" },
  "profile.bodyfat":        { en: "Body Fat", ru: "Жир" },
  "profile.measurements":   { en: "Measurements", ru: "Обмеры" },
  "profile.waist":          { en: "Waist", ru: "Талия" },
  "profile.neck":           { en: "Neck", ru: "Шея" },
  "profile.thigh":          { en: "Thigh", ru: "Бедро" },
  "profile.lifestyle":      { en: "Lifestyle", ru: "Образ жизни" },
  "profile.stress":         { en: "Stress", ru: "Стресс" },
  "profile.sleep":          { en: "Sleep", ru: "Сон" },
  "profile.diet":           { en: "Diet", ru: "Питание" },
  "profile.training":       { en: "Training", ru: "Тренировки" },
  "profile.experience":     { en: "Experience", ru: "Опыт" },
  "profile.activity":       { en: "Activity", ru: "Активность" },
  "profile.targets":        { en: "Daily Targets", ru: "Дневные цели" },
  "profile.calories":       { en: "Calories", ru: "Калории" },
  "profile.protein":        { en: "Protein", ru: "Белок" },
  "profile.steps":          { en: "Steps", ru: "Шаги" },
  "profile.mindset":        { en: "Week {w} Mindset", ru: "Психология недели {w}" },
  "profile.fatsecret":      { en: "FatSecret", ru: "FatSecret" },
  "profile.fs.connected":   { en: "✓ Connected — tap to manage", ru: "✓ Подключено — нажмите для управления" },
  "profile.fs.not":         { en: "Not connected", ru: "Не подключено" },
  "profile.language":       { en: "Language", ru: "Язык" },

  // ─── STRESS LABELS ────────────────────────────────────────────────────────
  "stress.1":               { en: "Very calm", ru: "Очень спокойно" },
  "stress.2":               { en: "Calm", ru: "Спокойно" },
  "stress.3":               { en: "Moderate", ru: "Умеренно" },
  "stress.4":               { en: "High", ru: "Высокий" },
  "stress.5":               { en: "Very stressed", ru: "Очень стрессово" },
  "sleep.1":                { en: "Excellent", ru: "Отличный" },
  "sleep.2":                { en: "Good", ru: "Хороший" },
  "sleep.3":                { en: "Average", ru: "Средний" },
  "sleep.4":                { en: "Poor", ru: "Плохой" },
  "sleep.5":                { en: "Very poor", ru: "Очень плохой" },
  "diet.1":                 { en: "Very clean", ru: "Очень чистое" },
  "diet.2":                 { en: "Clean", ru: "Чистое" },
  "diet.3":                 { en: "Mixed", ru: "Смешанное" },
  "diet.4":                 { en: "Poor", ru: "Плохое" },
  "diet.5":                 { en: "Very processed", ru: "Очень переработанное" },
  "training.display.none":  { en: "No / spontaneous", ru: "Нет / спонтанно" },
  "training.display.1_2x":  { en: "1–2× per week", ru: "1–2× в неделю" },
  "training.display.3plus": { en: "3+× per week", ru: "3+× в неделю" },

  // ─── FATSECRET PANEL ──────────────────────────────────────────────────────
  "fs.title":               { en: "FatSecret", ru: "FatSecret" },
  "fs.search":              { en: "Food Search", ru: "Поиск продуктов" },
  "fs.diary":               { en: "Today's Diary", ru: "Дневник сегодня" },
  "fs.settings":            { en: "API Config", ru: "Настройки API" },
  "fs.connected":           { en: "Connected", ru: "Подключено" },
  "fs.not_connected":       { en: "Not Connected", ru: "Не подключено" },
  "fs.sync_btn":            { en: "⚡ Sync Today's Diary", ru: "⚡ Синхр. дневник сегодня" },
  "fs.syncing":             { en: "⏳ Syncing diary…", ru: "⏳ Синхронизация…" },
  "fs.last_sync":           { en: "Last Sync — {n} foods", ru: "Последняя синхр. — {n} продуктов" },
  "fs.search.ph":           { en: "Search foods, e.g. chicken breast…", ru: "Поиск продуктов, напр. куриная грудка…" },
  "fs.no_results":          { en: "No results for \"{q}\"", ru: "Ничего не найдено для \"{q}\"" },
  "fs.add_diary":           { en: "Add to Diary ✓", ru: "В дневник ✓" },
  "fs.cancel":              { en: "Cancel", ru: "Отмена" },
  "fs.amount":              { en: "AMOUNT (g)", ru: "КОЛИЧЕСТВО (г)" },
  "fs.meal":                { en: "MEAL", ru: "ПРИЁМ ПИЩИ" },
  "fs.meals.breakfast":     { en: "Breakfast", ru: "Завтрак" },
  "fs.meals.lunch":         { en: "Lunch", ru: "Обед" },
  "fs.meals.dinner":        { en: "Dinner", ru: "Ужин" },
  "fs.meals.snacks":        { en: "Snacks", ru: "Перекусы" },
  "fs.totals":              { en: "Today's Totals", ru: "Итого за сегодня" },
  "fs.no_foods":            { en: "No foods logged today", ru: "Продукты за сегодня не добавлены" },
  "fs.add_more":            { en: "+ Add more foods", ru: "+ Добавить продукты" },
  "fs.connect":             { en: "Connect FatSecret", ru: "Подключить FatSecret" },
  "fs.connect.sub":         { en: "Auto-fill calories & protein from your diary", ru: "Автозаполнение калорий и белка из дневника" },
  "fs.demo":                { en: "Demo mode — local food database. Add API credentials in API Config to search 2.3M+ real foods.", ru: "Демо-режим — локальная база продуктов. Добавьте учётные данные API для поиска по 2,3 млн продуктов." },

  // ─── COACH DASHBOARD ──────────────────────────────────────────────────────
  "coach.title":            { en: "Team Overview", ru: "Обзор команды" },
  "coach.portal":           { en: "Coach Portal", ru: "Панель тренера" },
  "coach.exit":             { en: "← Exit", ru: "← Выйти" },
  "coach.athletes":         { en: "Athletes", ru: "Спортсмены" },
  "coach.active":           { en: "Active today", ru: "Активны сегодня" },
  "coach.avg_streak":       { en: "Avg streak", ru: "Ср. серия" },
  "coach.on_track":         { en: "On track", ru: "В графике" },
  "coach.tab.athletes":     { en: "Athletes", ru: "Спортсмены" },
  "coach.tab.insights":     { en: "Insights", ru: "Аналитика" },
  "coach.tab.notes":        { en: "Notes", ru: "Заметки" },
  "coach.logged":           { en: "✓ Logged", ru: "✓ Записано" },
  "coach.no_log":           { en: "No log", ru: "Нет записи" },
  "coach.leaderboard":      { en: "🏆 Streak Leaderboard", ru: "🏆 Рейтинг серий" },
  "coach.compliance":       { en: "Weekly Compliance", ru: "Соответствие за неделю" },
  "coach.notes.ph":         { en: "Notes for {name}…", ru: "Заметки для {name}…" },
  "coach.insights":         { en: "Team Insights", ru: "Аналитика команды" },
  "coach.notes.title":      { en: "Coach Notes", ru: "Заметки тренера" },

  // ─── WEEK THEMES ──────────────────────────────────────────────────────────
  "week.1.theme":           { en: "Foundation", ru: "Основа" },
  "week.2.theme":           { en: "Momentum", ru: "Импульс" },
  "week.3.theme":           { en: "Strength", ru: "Сила" },
  "week.4.theme":           { en: "Endurance", ru: "Выносливость" },
  "week.5.theme":           { en: "Power", ru: "Мощь" },
  "week.6.theme":           { en: "Flexibility", ru: "Гибкость" },
  "week.7.theme":           { en: "Recovery", ru: "Восстановление" },
  "week.8.theme":           { en: "Intensity", ru: "Интенсивность" },
  "week.9.theme":           { en: "Consistency", ru: "Постоянство" },
  "week.10.theme":          { en: "Challenge", ru: "Вызов" },
  "week.11.theme":          { en: "Balance", ru: "Баланс" },
  "week.12.theme":          { en: "Speed", ru: "Скорость" },
  "week.13.theme":          { en: "Control", ru: "Контроль" },
  "week.14.theme":          { en: "Peak", ru: "Пик" },
  "week.15.theme":          { en: "Taper", ru: "Снижение" },
  "week.16.theme":          { en: "Triumph", ru: "Триумф" },

  // ─── PROGRAM CONTENT — OVERVIEWS ─────────────────────────────────────────
  "week.1.overview":        { en: "Week 1 is about building habits. No heroics — just showing up consistently, learning your baseline, and establishing daily rituals of logging, moving, and eating with intention.", ru: "Неделя 1 — это формирование привычек. Никаких подвигов — просто регулярное выполнение, изучение своих показателей и установление ежедневных ритуалов: записи, движения и осознанного питания." },
  "week.2.overview":        { en: "Build on Week 1 — stack small wins daily. Slightly increase intensity, dial in sleep habits, and add a step count target. Make the routine feel normal.", ru: "Опираясь на неделю 1, накапливайте маленькие победы каждый день. Немного увеличьте интенсивность, наладьте привычки сна и добавьте цель по шагам. Сделайте режим привычным." },
  "week.3.overview":        { en: "Add resistance. Challenge your muscles with progressive overload — a little more tension than last week. Strength training is the single most effective tool for body recomposition.", ru: "Добавьте сопротивление. Нагружайте мышцы прогрессивной перегрузкой — чуть больше напряжения, чем на прошлой неделе. Силовые тренировки — самый эффективный инструмент рекомпозиции тела." },
  "week.4.overview":        { en: "Shift focus to cardiovascular endurance and recovery capacity. Longer, slower movement alongside strength work. This builds your heart, lungs, and ability to sustain effort.", ru: "Переключитесь на кардиовыносливость и способность к восстановлению. Более долгие, медленные движения наряду с силовой работой. Это укрепляет сердце, лёгкие и способность выдерживать нагрузку." },
  "week.5.overview":        { en: "You've built the foundation. Now apply it. Week 5 introduces power — producing force quickly. Translates to everything: sports performance, injury resilience, and metabolic rate.", ru: "Фундамент заложен. Теперь применяйте его. Неделя 5 вводит мощь — способность быстро генерировать усилие. Это влияет на всё: спортивные результаты, устойчивость к травмам и обмен веществ." },
  "week.6.overview":        { en: "A deliberate deload — planned reduction in intensity to let your body consolidate 5 weeks of work. The best athletes schedule recovery as intentionally as training.", ru: "Намеренная разгрузка — плановое снижение интенсивности, чтобы тело усвоило 5 недель работы. Лучшие спортсмены планируют восстановление так же намеренно, как и тренировки." },
  "week.7.overview":        { en: "Build on the deload. Explore the systems that keep you resilient: sleep optimisation, stress management, gut health. These factors account for ~40% of training outcomes.", ru: "Продолжайте разгрузку. Изучайте системы, поддерживающие устойчивость: оптимизация сна, управление стрессом, здоровье кишечника. Эти факторы составляют ~40% результатов тренировок." },
  "week.8.overview":        { en: "The halfway point. Turn up the intensity — higher volume, less rest, push to genuine failure on key sets. You're ready for this.", ru: "Середина пути. Повысьте интенсивность — больший объём, меньше отдыха, доведите ключевые подходы до настоящего отказа. Вы готовы к этому." },
  "week.9.overview":        { en: "The hardest psychological phase — novelty has passed, results aren't fully visible yet. Trust the process. The compound effect is happening under the surface.", ru: "Самый сложный психологический этап — новизна прошла, результаты ещё не полностью видны. Доверяйте процессу. Эффект накопления происходит под поверхностью." },
  "week.10.overview":       { en: "Introduce a third training day and reduce rest periods. Build mental and physical resilience. Discover how much more capable you are than you thought.", ru: "Добавьте третий тренировочный день и сократите периоды отдыха. Развивайте ментальную и физическую устойчивость. Откройте, на сколько вы способны больше, чем думали." },
  "week.11.overview":       { en: "Balance — not physical, but integration. Training hard, eating well, sleeping deeply, managing stress, and feeling good are not competing priorities. They reinforce each other.", ru: "Баланс — не физический, а интегральный. Упорные тренировки, правильное питание, глубокий сон, управление стрессом и хорошее самочувствие — не конкурирующие приоритеты. Они усиливают друг друга." },
  "week.12.overview":       { en: "Three-quarters done. Add explosive speed work — faster contractions, plyometric movements. Body composition shifts become most visible. Speed training is one of the most underrated fat-loss tools.", ru: "Три четверти пути позади. Добавьте взрывную работу на скорость — более быстрые сокращения, плиометрические движения. Изменения в составе тела становятся наиболее заметными." },
  "week.13.overview":       { en: "Control — physical and mental. In training, slow the eccentric phase to maximise muscle damage and growth. In life, work on responding rather than reacting.", ru: "Контроль — физический и ментальный. На тренировках замедлите эксцентрическую фазу для максимального роста мышц. В жизни работайте над осознанными реакциями, а не импульсивными." },
  "week.14.overview":       { en: "Your peak training week — highest volume and intensity of the entire program. Your strength, endurance, movement quality, and mindset are at their highest. Leave nothing on the table.", ru: "Ваша пиковая тренировочная неделя — максимальный объём и интенсивность за всю программу. Ваша сила, выносливость, качество движений и настрой на высшем уровне. Выложитесь полностью." },
  "week.15.overview":       { en: "Tapering — reduce volume while maintaining intensity. You've done the work. Let your body fully absorb 14 weeks of adaptation before the final Week 16.", ru: "Снижение нагрузки — уменьшите объём, сохранив интенсивность. Работа выполнена. Позвольте телу полностью усвоить 14 недель адаптации перед финальной 16-й неделей." },
  "week.16.overview":       { en: "Week 16. The final week. A celebration and a beginning. Your final benchmarks will show exactly how far you've come. Then we set you up for what comes next.", ru: "Неделя 16. Финальная неделя. Праздник и начало. Ваши финальные показатели покажут, как далеко вы продвинулись. Затем мы готовим вас к тому, что будет дальше." },

  // ─── PROGRAM CONTENT — TRAINING TITLES ───────────────────────────────────
  "training.1.title":       { en: "Full Body Activation", ru: "Активация всего тела" },
  "training.2.title":       { en: "Lower Body Power", ru: "Сила нижней части тела" },
  "training.3.title":       { en: "Upper Body Push & Pull", ru: "Жим и тяга верхней части тела" },
  "training.4.title":       { en: "Steady State Cardio", ru: "Кардио в стабильном темпе" },
  "training.5.title":       { en: "Full Body Compound Lifts", ru: "Базовые упражнения на всё тело" },
  "training.6.title":       { en: "Flexibility & Mobility Circuit", ru: "Растяжка и подвижность" },
  "training.7.title":       { en: "Back to Strength — Reset", ru: "Возврат к силе — сброс" },
  "training.8.title":       { en: "High Volume Upper/Lower Circuit", ru: "Высокообъёмный сплит верх/низ" },
  "training.9.title":       { en: "Progressive Overload Test", ru: "Тест прогрессивной перегрузки" },
  "training.10.title":      { en: "Three-Day Split", ru: "Трёхдневный сплит" },
  "training.11.title":      { en: "Strength & Skill", ru: "Сила и техника" },
  "training.12.title":      { en: "Power & Plyometric Circuit", ru: "Мощь и плиометрика" },
  "training.13.title":      { en: "Tempo Training (3-1-2)", ru: "Темповые тренировки (3-1-2)" },
  "training.14.title":      { en: "Maximum Effort Week", ru: "Неделя максимальных усилий" },
  "training.15.title":      { en: "Taper — Maintain Intensity, Cut Volume", ru: "Снижение — сохранить интенсивность, уменьшить объём" },
  "training.16.title":      { en: "The Final Benchmark", ru: "Финальный тест" },

  // ─── PROGRAM CONTENT — NUTRITION TITLES ──────────────────────────────────
  "nutrition.1.title":      { en: "Protein at Every Meal", ru: "Белок в каждом приёме пищи" },
  "nutrition.2.title":      { en: "Eat More Colour", ru: "Больше цвета в тарелке" },
  "nutrition.3.title":      { en: "Post-Workout Nutrition", ru: "Питание после тренировки" },
  "nutrition.4.title":      { en: "Carbs Are Not the Enemy", ru: "Углеводы — не враг" },
  "nutrition.5.title":      { en: "Calorie Awareness", ru: "Осознанность калорий" },
  "nutrition.6.title":      { en: "Anti-Inflammatory Eating", ru: "Противовоспалительное питание" },
  "nutrition.7.title":      { en: "Gut Health Basics", ru: "Основы здоровья кишечника" },
  "nutrition.8.title":      { en: "Calorie Periodisation", ru: "Периодизация калорий" },
  "nutrition.9.title":      { en: "Protein Timing Mastery", ru: "Мастерство тайминга белка" },
  "nutrition.10.title":     { en: "Pre-Sleep Protein", ru: "Белок перед сном" },
  "nutrition.11.title":     { en: "The 80/20 Rule", ru: "Правило 80/20" },
  "nutrition.12.title":     { en: "Creatine & Performance", ru: "Креатин и результативность" },
  "nutrition.13.title":     { en: "Mindful Eating", ru: "Осознанное питание" },
  "nutrition.14.title":     { en: "Peak Week Fuelling", ru: "Питание на пиковой неделе" },
  "nutrition.15.title":     { en: "Maintenance and Preparation", ru: "Поддержание и подготовка" },
  "nutrition.16.title":     { en: "Building for Life", ru: "Строим на всю жизнь" },

  // ─── PROGRAM CONTENT — MINDSET TITLES ────────────────────────────────────
  "mindset.1.title":        { en: "Identity, Not Goals", ru: "Идентичность, а не цели" },
  "mindset.2.title":        { en: "Track Without Judgment", ru: "Отслеживай без осуждения" },
  "mindset.3.title":        { en: "Embrace Discomfort", ru: "Принять дискомфорт" },
  "mindset.4.title":        { en: "The 1% Rule", ru: "Правило 1%" },
  "mindset.5.title":        { en: "Competition With Yourself", ru: "Соревнование с собой" },
  "mindset.6.title":        { en: "Rest Is Productive", ru: "Отдых — это продуктивно" },
  "mindset.7.title":        { en: "The Process Is the Goal", ru: "Процесс — это и есть цель" },
  "mindset.8.title":        { en: "Halfway Reflection", ru: "Рефлексия на середине пути" },
  "mindset.9.title":        { en: "When Motivation Fails, Use Discipline", ru: "Когда мотивация уходит, включай дисциплину" },
  "mindset.10.title":       { en: "The Challenge Mindset", ru: "Мышление вызова" },
  "mindset.11.title":       { en: "Zoom Out", ru: "Смотри шире" },
  "mindset.12.title":       { en: "Speed of Trust", ru: "Скорость доверия" },
  "mindset.13.title":       { en: "Respond, Don't React", ru: "Реагируй, не реагируй импульсивно" },
  "mindset.14.title":       { en: "The Final Push", ru: "Финальный рывок" },
  "mindset.15.title":       { en: "Gratitude and Anticipation", ru: "Благодарность и предвкушение" },
  "mindset.16.title":       { en: "This Is Just the Beginning", ru: "Это только начало" },

  // ─── DAY TASK TITLES & DESCRIPTIONS ──────────────────────────────────────
  "task.activation.title":  { en: "Morning Activation", ru: "Утренняя активация" },
  "task.activation.task":   { en: "Complete your Week {w} Full Body Activation session. Take your time, focus on form, not speed.", ru: "Выполните сессию активации всего тела для недели {w}. Не торопитесь, сосредоточьтесь на технике, а не скорости." },
  "task.protein.title":     { en: "Protein at Breakfast", ru: "Белок за завтраком" },
  "task.protein.task":      { en: "Eat at least 20g of protein within 30 minutes of waking. Log it.", ru: "Съешьте не менее 20 г белка в течение 30 минут после пробуждения. Запишите это." },
  "task.why.title":         { en: "Your Why", ru: "Ваше «зачем»" },
  "task.why.task":          { en: "Write down in 3 sentences why you started this program. Keep it somewhere visible.", ru: "Напишите в 3 предложениях, почему вы начали эту программу. Держите это на видном месте." },
  "task.walk.title":        { en: "10-Minute Walk", ru: "10-минутная прогулка" },
  "task.walk.task":         { en: "Walk outside for exactly 10 minutes, no phone. Morning is ideal.", ru: "Прогуляйтесь на улице ровно 10 минут без телефона. Идеально — утром." },
  "task.hydration.title":   { en: "Hydration Baseline", ru: "Базовый уровень гидратации" },
  "task.hydration.task":    { en: "Drink 2.5 litres of water today. Set reminders, track it.", ru: "Выпейте 2,5 литра воды сегодня. Установите напоминания, отслеживайте." },
  "task.pushup.title":      { en: "Push-Up Practice", ru: "Практика отжиманий" },
  "task.pushup.task":       { en: "3 sets of push-ups with 60s rest. Any variation — wall, knee, or full.", ru: "3 подхода отжиманий с отдыхом 60 секунд. Любой вариант — от стены, с колен или полные." },
  "task.reflect.title":     { en: "Rest & Reflect", ru: "Отдых и рефлексия" },
  "task.reflect.task":      { en: "No training today. Write 3 things your body did well this week.", ru: "Сегодня без тренировок. Запишите 3 вещи, которые ваше тело делало хорошо на этой неделе." },

  // ─── TIP CATEGORIES ───────────────────────────────────────────────────────
  "tip.training":           { en: "Training", ru: "Тренировка" },
  "tip.nutrition":          { en: "Nutrition", ru: "Питание" },
  "tip.mindset":            { en: "Mindset", ru: "Психология" },
  "tip.recovery":           { en: "Recovery", ru: "Восстановление" },

  // ─── LOADING ──────────────────────────────────────────────────────────────
  "app.loading":            { en: "Loading…", ru: "Загрузка…" },

  // ─── UNITS ────────────────────────────────────────────────────────────────
  "unit.kg":                { en: "kg", ru: "кг" },
  "unit.cm":                { en: "cm", ru: "см" },
  "unit.kcal":              { en: "kcal", ru: "ккал" },
  "unit.g":                 { en: "g", ru: "г" },
  "unit.steps":             { en: "steps", ru: "шагов" },
  "unit.years":             { en: "y", ru: "л" },
  "unit.min":               { en: "min", ru: "мин" },
  "unit.percent":           { en: "%", ru: "%" },
};

// ─── TRANSLATION FUNCTION ─────────────────────────────────────────────────────
// Call: t("key") or t("key", { name: "Alex", w: 3 })
export function createTranslator(lang = "en") {
  return function t(key, vars = {}) {
    const entry = TRANSLATIONS[key];
    if (!entry) return key; // fallback: show key itself
    let str = entry[lang] || entry["en"] || key;
    // Replace {variable} placeholders
    Object.entries(vars).forEach(([k, v]) => {
      str = str.replace(new RegExp(`\\{${k}\\}`, "g"), v);
    });
    return str;
  };
}
